const employees = [
  {
    id: 1,
    firstName: "Rahul",
    email: "employee1@gmail.com",
    password: "123",
    taskNumber: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Design Login Page",
        taskDescription: "Create a responsive login page",
        taskDate: "2026-06-25",
        category: "Design",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Build Dashboard",
        taskDescription: "Create employee dashboard",
        taskDate: "2026-06-26",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Fix Profile Page",
        taskDescription: "Update user profile form UI",
        taskDate: "2026-06-24",
        category: "UI",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Resolve Sidebar Issue",
        taskDescription: "Fix sidebar overflow on mobile",
        taskDate: "2026-06-23",
        category: "Bug Fix",
      },
    ],
  },
  {
    id: 2,
    firstName: "Priya",
    email: "employee2@gmail.com",
    password: "123",
    taskNumber: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Review UI Mockups",
        taskDescription: "Check design consistency across pages",
        taskDate: "2026-06-25",
        category: "Design",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Create Footer Section",
        taskDescription: "Build responsive footer layout",
        taskDate: "2026-06-26",
        category: "Frontend",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Implement Search Filter",
        taskDescription: "Add search and filter functionality",
        taskDate: "2026-06-26",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Update Color Palette",
        taskDescription: "Improve theme colors for accessibility",
        taskDate: "2026-06-24",
        category: "Design",
      },
    ],
  },
  {
    id: 3,
    firstName: "Aarav",
    email: "employee3@gmail.com",
    password: "123",
    taskNumber: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Fix Navbar Bug",
        taskDescription: "Resolve responsive menu issue",
        taskDate: "2026-06-24",
        category: "Bug Fix",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Write API Integration",
        taskDescription: "Connect frontend with backend API",
        taskDate: "2026-06-26",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Test Login Flow",
        taskDescription: "Verify login validation and redirect",
        taskDate: "2026-06-25",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Fix Button Alignment",
        taskDescription: "Correct spacing in header buttons",
        taskDate: "2026-06-23",
        category: "UI",
      },
    ],
  },
  {
    id: 4,
    firstName: "Ananya",
    email: "employee4@gmail.com",
    password: "123",
    taskNumber: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Create Footer",
        taskDescription: "Design and implement site footer",
        taskDate: "2026-06-25",
        category: "UI",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Refactor Header",
        taskDescription: "Improve header component structure",
        taskDate: "2026-06-26",
        category: "Frontend",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Improve Accessibility",
        taskDescription: "Check color contrast and labels",
        taskDate: "2026-06-26",
        category: "Accessibility",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Update Hero Section",
        taskDescription: "Finalize homepage hero content",
        taskDate: "2026-06-24",
        category: "UI",
      },
    ],
  },
  {
    id: 5,
    firstName: "Vikram",
    email: "employee5@gmail.com",
    password: "123",
    taskNumber: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Update Profile Page",
        taskDescription: "Add edit profile features",
        taskDate: "2026-06-24",
        category: "Frontend",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Optimize Images",
        taskDescription: "Compress and lazy-load assets",
        taskDate: "2026-06-26",
        category: "Performance",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Fix Form Validation",
        taskDescription: "Improve input error handling",
        taskDate: "2026-06-25",
        category: "Bug Fix",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Resolve Modal Issue",
        taskDescription: "Close modal on overlay click",
        taskDate: "2026-06-23",
        category: "UI",
      },
    ],
  },
  {
    id: 6,
    firstName: "Rohan",
    email: "employee6@gmail.com",
    password: "123",
    taskNumber: {
      active: 3,
      newTask: 2,
      completed: 4,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Set Up Authentication",
        taskDescription: "Implement login flow with token",
        taskDate: "2026-06-23",
        category: "Backend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Create Reports Cards",
        taskDescription: "Design report summary widgets",
        taskDate: "2026-06-24",
        category: "Dashboard",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Fix API Loading State",
        taskDescription: "Show spinner while fetching data",
        taskDate: "2026-06-26",
        category: "Frontend",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Build Reports Page",
        taskDescription: "Create analytics reports screen",
        taskDate: "2026-06-26",
        category: "Dashboard",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Add Export CSV",
        taskDescription: "Export report data as CSV",
        taskDate: "2026-06-26",
        category: "Utility",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Prepare Team Overview",
        taskDescription: "Summarize weekly team progress",
        taskDate: "2026-06-25",
        category: "Documentation",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Improve Table Sorting",
        taskDescription: "Add ascending and descending sort",
        taskDate: "2026-06-24",
        category: "Frontend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Test Dark Mode",
        taskDescription: "Verify theme switching behavior",
        taskDate: "2026-06-23",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Fix Badge Counter",
        taskDescription: "Update unread count display",
        taskDate: "2026-06-22",
        category: "Bug Fix",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Resolve Chart Crash",
        taskDescription: "Fix error when chart data is empty",
        taskDate: "2026-06-21",
        category: "Bug Fix",
      },
    ],
  },
  {
    id: 7,
    firstName: "Kavya",
    email: "employee7@gmail.com",
    password: "123",
    taskNumber: {
      active: 2,
      newTask: 1,
      completed: 5,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Refactor Components",
        taskDescription: "Clean up reusable UI components",
        taskDate: "2026-06-24",
        category: "Code Quality",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Fix Dropdown Alignment",
        taskDescription: "Align dropdown menu properly",
        taskDate: "2026-06-26",
        category: "UI",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Add Toast Notifications",
        taskDescription: "Show success and error alerts",
        taskDate: "2026-06-26",
        category: "UI",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Update Dashboard Icons",
        taskDescription: "Replace outdated icons",
        taskDate: "2026-06-25",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Improve Table Layout",
        taskDescription: "Make table responsive",
        taskDate: "2026-06-24",
        category: "Frontend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Test Search Bar",
        taskDescription: "Check search behavior on typing",
        taskDate: "2026-06-23",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Document Components",
        taskDescription: "Write component usage notes",
        taskDate: "2026-06-22",
        category: "Documentation",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Review PR Comments",
        taskDescription: "Check feedback from reviewers",
        taskDate: "2026-06-21",
        category: "Review",
      },
    ],
  },
  {
    id: 8,
    firstName: "Arjun",
    email: "employee8@gmail.com",
    password: "123",
    taskNumber: {
      active: 4,
      newTask: 2,
      completed: 3,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Design Sidebar",
        taskDescription: "Create a collapsible sidebar",
        taskDate: "2026-06-25",
        category: "Design",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Fix Button Styles",
        taskDescription: "Update button hover states",
        taskDate: "2026-06-26",
        category: "UI",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Improve Card Spacing",
        taskDescription: "Adjust spacing in dashboard cards",
        taskDate: "2026-06-24",
        category: "Frontend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Optimize Grid Layout",
        taskDescription: "Reduce layout shifts on resize",
        taskDate: "2026-06-23",
        category: "Performance",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Add Pagination",
        taskDescription: "Paginate table records",
        taskDate: "2026-06-26",
        category: "Development",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Create Breadcrumbs",
        taskDescription: "Add page navigation breadcrumbs",
        taskDate: "2026-06-26",
        category: "UI",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Test Responsive Grid",
        taskDescription: "Check grid on tablet screens",
        taskDate: "2026-06-25",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Document Layout Rules",
        taskDescription: "Write layout guidelines",
        taskDate: "2026-06-24",
        category: "Documentation",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Review Theme Colors",
        taskDescription: "Confirm final color palette",
        taskDate: "2026-06-23",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Fix Icon Overflow",
        taskDescription: "Stop icons from overlapping text",
        taskDate: "2026-06-22",
        category: "Bug Fix",
      },
    ],
  },
  {
    id: 9,
    firstName: "Sneha",
    email: "employee9@gmail.com",
    password: "123",
    taskNumber: {
      active: 1,
      newTask: 1,
      completed: 6,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Improve Search UX",
        taskDescription: "Make search more user-friendly",
        taskDate: "2026-06-24",
        category: "UI/UX",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Test Mobile Layout",
        taskDescription: "Check responsiveness on phones",
        taskDate: "2026-06-26",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Update FAQ Page",
        taskDescription: "Refresh help content",
        taskDate: "2026-06-25",
        category: "Content",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Fix Footer Links",
        taskDescription: "Repair broken anchor links",
        taskDate: "2026-06-24",
        category: "Bug Fix",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Write Release Notes",
        taskDescription: "Summarize latest app updates",
        taskDate: "2026-06-23",
        category: "Documentation",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Review Accessibility",
        taskDescription: "Check keyboard navigation",
        taskDate: "2026-06-22",
        category: "Accessibility",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Check Button States",
        taskDescription: "Verify disabled and hover states",
        taskDate: "2026-06-21",
        category: "Frontend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Update Gallery Images",
        taskDescription: "Replace outdated product images",
        taskDate: "2026-06-20",
        category: "Design",
      },
    ],
  },
  {
    id: 10,
    firstName: "Aditya",
    email: "employee10@gmail.com",
    password: "123",
    taskNumber: {
      active: 5,
      newTask: 3,
      completed: 2,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Deploy App",
        taskDescription: "Deploy latest build to production",
        taskDate: "2026-06-25",
        category: "DevOps",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Monitor Logs",
        taskDescription: "Watch for server errors",
        taskDate: "2026-06-26",
        category: "DevOps",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Fix Build Warning",
        taskDescription: "Resolve bundler warning",
        taskDate: "2026-06-24",
        category: "Bug Fix",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Update Env Config",
        taskDescription: "Change environment variables",
        taskDate: "2026-06-23",
        category: "DevOps",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Restart Worker",
        taskDescription: "Restart background worker process",
        taskDate: "2026-06-22",
        category: "Backend",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Review Code",
        taskDescription: "Inspect pull requests and comments",
        taskDate: "2026-06-26",
        category: "Review",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Setup Monitoring",
        taskDescription: "Add error tracking tool",
        taskDate: "2026-06-26",
        category: "DevOps",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Check Deployment Status",
        taskDescription: "Confirm release is stable",
        taskDate: "2026-06-26",
        category: "DevOps",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Finish Server Migration",
        taskDescription: "Move backend to new host",
        taskDate: "2026-06-25",
        category: "Infrastructure",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Test Backup Restore",
        taskDescription: "Verify restore procedure",
        taskDate: "2026-06-24",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Fix Cron Job Failure",
        taskDescription: "Repair scheduled task issue",
        taskDate: "2026-06-23",
        category: "Bug Fix",
      },
    ],
  },
  {
    id: 11,
    firstName: "Ishita",
    email: "employee11@gmail.com",
    password: "123",
    taskNumber: {
      active: 2,
      newTask: 1,
      completed: 4,
      failed: 2,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Prepare Meeting Notes",
        taskDescription: "Summarize client meeting points",
        taskDate: "2026-06-24",
        category: "Documentation",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Check Email Templates",
        taskDescription: "Review automated email content",
        taskDate: "2026-06-26",
        category: "Content",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Fix Form Validation",
        taskDescription: "Add required field checks",
        taskDate: "2026-06-26",
        category: "Bug Fix",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Update Help Center",
        taskDescription: "Improve support articles",
        taskDate: "2026-06-25",
        category: "Content",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Test Search Results",
        taskDescription: "Verify result order and accuracy",
        taskDate: "2026-06-24",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Review Feedback",
        taskDescription: "Analyze user comments",
        taskDate: "2026-06-23",
        category: "Review",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Fix Empty State UI",
        taskDescription: "Improve no-data screen design",
        taskDate: "2026-06-22",
        category: "UI",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Resolve Print Issue",
        taskDescription: "Fix page print formatting",
        taskDate: "2026-06-21",
        category: "Bug Fix",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Repair Download Button",
        taskDescription: "Make file download work again",
        taskDate: "2026-06-20",
        category: "Frontend",
      },
    ],
  },
]
const admin = {
  id: 1,
  email: "admin@gmail.com",
  password: "123",
};

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};